config/routes.rb
Restserveruff::Application.routes.draw do

  match '/estabelecimentos/proximos', :controller => 'estabelecimentos', :action => 'proximos'
  match '/estabelecimentos/busca', :controller => 'estabelecimentos', :action => 'busca'
  match '/usuarios/login', :controller => 'usuarios', :action => 'login'
  
  resources :usuarios, :produtos, :estabelecimentos, :caracteristicas, :precos
  
  resources :usuarios do
    resources :favoritos
  end

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :nome, :tipo
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @produto }
    end
  end

  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html  { redirect_to(@produto, :notice => 'O Produto foi criado.') }
        format.json  { render :json => @produto, :status => :created, :location => @produto }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html  { redirect_to(@produto, :notice => 'O Produto foi atualizado.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @produto = Produto.find(params[:id])
  end

  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end

  def index
    @lista = Produto.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @lista }
    end
  end

  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @produto }
    end

  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@produto.errors.count, "error") %> o produto nao pode ser salvo:</h2>
    <ul>
    <% @produto.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit "ok"%>
  </div>
<% end %>

app/views/produtos/create.html.erb
<h1>Produtos#create</h1>
<p>Find me in app/views/produtos/create.html.erb</p>

app/views/produtos/destroy.html.erb
<h1>Produtos#destroy</h1>
<p>Find me in app/views/produtos/destroy.html.erb</p>

app/views/produtos/edit.html.erb
<h1>Alterando produto</h1>
 
<%= render 'form' %>
 
<%= link_to 'Exibir', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<h1>Produtos</h1>
 
<table>
  <tr>
    <th>Nome</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @lista.each do |produto| %>
  <tr>
    <td><%= produto.nome %></td>
    <td><%= link_to 'Exibir', produto %></td>
    <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
    <td><%= link_to 'Deletar', produto, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'Novo produto', new_produto_path %> 

app/views/produtos/new.html.erb
<h1>Novo produto</h1>
 
<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Nome:</b>
  <%= @produto.nome %>
</p>
<p>
  <b>:tipo</b>
  <%= @produto.tipo %>
</p>

 
<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/update.html.erb
<h1>Produtos#update</h1>
<p>Find me in app/views/produtos/update.html.erb</p>