config/routes.rb
Restserveruff::Application.routes.draw do

  match '/estabelecimentos/proximos', :controller => 'estabelecimentos', :action => 'proximos'
  match '/estabelecimentos/busca', :controller => 'estabelecimentos', :action => 'busca'
  match '/usuarios/login', :controller => 'usuarios', :action => 'login'
  
  resources :usuarios, :produtos, :estabelecimentos, :caracteristicas, :precos
  
  resources :usuarios do
    resources :favoritos
  end

end

app/models/favorito.rb
class Favorito < ActiveRecord::Base
  attr_accessible :estabelecimento_id, :usuario_id
  
  belongs_to :usuario
  belongs_to :estabelecimento
end

app/controllers/favoritos_controller.rb
class FavoritosController < ApplicationController
  
  def new
    @usuario = Usuario.find(params[:usuario_id])
    @favorito = Favorito.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @favorito }
    end
  end

  def create
    #:usuario_id mas é login que vem
    @usuario = Usuario.find_by_login(params[:usuario_id])
    @favorito = Favorito.new
    @favorito.usuario_id = @usuario.id
    
    @favorito.estabelecimento_id = params[:estabelecimento_id]
    @estabelecimento = Estabelecimento.find(params[:estabelecimento_id])   
    
    @usuario.estabelecimentos.push(@estabelecimento)

    respond_to do |format|
      if @usuario.save
        format.html  { redirect_to :action => :index , :usuario_id => @usuario.id, :notice => 'O Favorito foi adicionado.' }
        format.json  { render :json => @favorito, :status => :created, :location => @favorito }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @favorito.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    #:usuario_id mas é login que vem
    @usuario = Usuario.find_by_login(params[:usuario_id])
    @favorito = Favorito.find_all_by_usuario_id_and_estabelecimento_id(@usuario.id,params[:id]).first
    Favorito.delete_all(["usuario_id = ? AND estabelecimento_id = ?",@favorito.usuario_id,@favorito.estabelecimento_id])

    respond_to do |format|
      format.html { redirect_to usuario_favoritos_url(@usuario) }
      format.json { head :no_content }
    end
  end

  def index
    #:usuario_id mas é login que vem
    @usuario = Usuario.find_by_login(params[:usuario_id])
    @favoritos = Favorito.find_all_by_usuario_id(@usuario.id)
    @lista = Array.new
    @favoritos.each do |favorito|
      favorito.estabelecimento.favorito = true
      @lista.push(favorito.estabelecimento)
    end

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @lista, :include => {:precos =>{:only => :valor, :include =>:produto } , 
      :caracteristicas => {:only => [:nome, :id]} } }
    end
  end
  
  def show
    
  end

end

app/helpers/favoritos_helper.rb
module FavoritosHelper
end

app/views/favoritos/_form.html.erb
<%= form_for [@usuario , @favorito] do |f| %>
  <% if @favorito.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@favorito.errors.count, "error") %> o favorito nao pode ser salvo:</h2>
    <ul>
    <% @favorito.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :estabelecimento_id %><br />
    <%= f.text_field :estabelecimento_id %>
  </div>
  <div class="actions">
    <%= f.submit "ok"%>
  </div>
<% end %>

app/views/favoritos/create.html.erb
<h1>Favoritos#create</h1>
<p>Find me in app/views/favoritos/create.html.erb</p>

app/views/favoritos/destroy.html.erb
<h1>Favoritos#destroy</h1>
<p>Find me in app/views/favoritos/destroy.html.erb</p>

app/views/favoritos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Favoritos</h1>
 
<table>
 
<%@lista.each do |estabelecimento|%> 
  <tr>	
  	<td><%= estabelecimento.nome %></td>
	<td><%= link_to 'Remover', usuario_favorito_path(@usuario.id,estabelecimento.id), :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<%end %>  
</table>
 
<br />
 
<%= link_to 'Adicionar favorito', new_usuario_favorito_path(@usuario.id) %> 

app/views/favoritos/new.html.erb
<h1>Adcionar favorito</h1>
 
<%= render 'form' %>

<%= link_to 'Voltar', usuario_favorito_path(@usuario) %>

app/views/favoritos/show.html.erb
<p id="notice"><%= notice %></p>
 
<%= link_to 'Voltar', usuario_favoritos_path(@usuario.id) %>