config/routes.rb
Restserveruff::Application.routes.draw do

  match '/estabelecimentos/proximos', :controller => 'estabelecimentos', :action => 'proximos'
  match '/estabelecimentos/busca', :controller => 'estabelecimentos', :action => 'busca'
  match '/usuarios/login', :controller => 'usuarios', :action => 'login'
  
  resources :usuarios, :produtos, :estabelecimentos, :caracteristicas, :precos
  
  resources :usuarios do
    resources :favoritos
  end

end

app/models/estabelecimento.rb
class Estabelecimento < ActiveRecord::Base
  attr_accessible :endereco, :latitude, :longitude, :nome, :gostei, :telefone, :caracteristicas,  :id
  
  has_many :precos
  has_many :favoritos
  has_and_belongs_to_many :caracteristicas
  has_many :produtos, :through => :precos
  has_many :usuarios, :through => :favoritos
end

app/controllers/estabelecimentos_controller.rb
class EstabelecimentosController < ApplicationController
  include EstabelecimentosHelper
  def new
    @estabelecimento = Estabelecimento.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @estabelecimento }
    end
  end

  def create
    @estabelecimento = Estabelecimento.new(params[:estabelecimento])

    respond_to do |format|
      if @estabelecimento.save
        format.html  { redirect_to(@estabelecimento, :notice => 'O estabelecimento foi criado.') }
        format.json  { render :json => @estabelecimento, :status => :created, :location => @estabelecimento }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @estabelecimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @estabelecimento = Estabelecimento.find(params[:id])

    respond_to do |format|
      if @estabelecimento.update_attributes(params[:estabelecimento])
        format.html  { redirect_to(@estabelecimento, :notice => 'O estabelecimento foi atualizado.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @estabelecimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @estabelecimento = Estabelecimento.find(params[:id])
  end

  def destroy
    @estabelecimento = Estabelecimento.find(params[:id])
    @estabelecimento.destroy

    respond_to do |format|
      format.html { redirect_to estabelecimentos_url }
      format.json { head :no_content }
    end
  end

  def index
    @lista = Estabelecimento.all
    if (params[:token] != nil)
      user = Usuario.find_by_token(params[:token])
      @favoritos = Favorito.find_all_by_usuario_id(user.id)
      @lista.each do |estab|
        estab.favorito = false
        @favoritos.each do |fav|
          if (fav.estabelecimento_id == estab.id)
            estab.favorito = true
            break
          end
        end   
      end
    end

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @lista, :include => {:precos =>{:only => :valor, :include =>:produto } , 
      :caracteristicas => {:only => [:nome, :id]} } }
    end
  end

  def show
    @estabelecimento = Estabelecimento.find(params[:id])
    @estabelecimento.favorito = false
    if (params[:token] != nil)
      user = Usuario.find_by_token(params[:token])
      @favoritos = Favorito.find_all_by_usuario_id(user.id)
      @favoritos.each do |fav|
        if (fav.estabelecimento_id == @estabelecimento.id)
          @estabelecimento.favorito = true
          break
        end
      end   
    end


    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @estabelecimento, :include => {:precos =>{:only => :valor, :include => {:produto =>{:only => :nome}} }, :caracteristicas => {:only => [:nome]}  }  }
    end

  end

#Ex por URL
#http://localhost:3000/estabelecimentos/proximos?raio=100&latitude=-22.903811&longitude=-43.104175
#http://maparadar.com/forum/viewtopic.php?f=145&t=5181
#gmaps esta em graus decimais
#https://support.google.com/maps/answer/2533464?hl=pt
  def proximos
    @lista = Array.new
    estabelecimentos = Estabelecimento.all
    if (params[:token] != nil)
      user = Usuario.find_by_token(params[:token])
      @favoritos = Favorito.find_all_by_usuario_id(user.id)
      estabelecimentos.each do |estab|
        estab.favorito = false
        @favoritos.each do |fav|
          if (fav.estabelecimento_id == estab.id)
            estab.favorito = true
            break
          end
        end   
      end
    end
    
    raio = params[:raio]
    if (raio == nil)
      raio = 1000
    end
    estabelecimentos.each do |estab|
      dist = distancia(params[:latitude].to_f, params[:longitude].to_f,estab.latitude, estab.longitude)
      if (dist.to_f <= raio.to_f && dist.to_f != 0.0)
        if (estab.favorito == nil)
          estab.favorito = false
        end
        @lista.push(estab)
      end
    end
    
    respond_to do |format|
      format.html  # proximos.html.erb
      format.json  { render :json => @lista, :include => {:precos =>{:only => :valor, :include =>:produto } , 
      :caracteristicas => {:only => [:nome, :id]} } }
    end
    
  end
  
#Ex por URL
#http://localhost:3000/estabelecimentos/busca?caracteristica=31
#31 é pizzaria
  def busca
    if (params[:tipo] == "nome")
      @lista = Estabelecimento.find(:all, :include=>:caracteristicas, :conditions => ['LOWER(estabelecimentos.nome) LIKE ? ','%'+params[:nome].downcase+'%'])
    else 
      if (params[:tipo] == "caracteristica")
        @lista = Estabelecimento.find(:all, :include=>:caracteristicas, :conditions => ['caracteristicas.id = ' + params[:caracteristica]])
      end
    end
    if (params[:token] != nil)
      user = Usuario.find_by_token(params[:token])
      @favoritos = Favorito.find_all_by_usuario_id(user.id)
      @lista.each do |estab|
        estab.favorito = false
        @favoritos.each do |fav|
          if (fav.estabelecimento_id == estab.id)
            estab.favorito = true
            break
          end
        end   
      end
    end
    
    
    respond_to do |format|
      format.html  # busca.html.erb
      format.json  { render :json => @lista, :include => {:precos =>{:only => :valor, :include =>:produto } , 
      :caracteristicas => {:only => [:nome, :id]} } }
    end
  end

end

app/helpers/estabelecimentos_helper.rb
module EstabelecimentosHelper
  
  def distancia(lat1, long1, lat2, long2)
    #Fórmula de Haversine
    pi = 3.1415927
    lat1 = lat1 * pi / 180
    long1 = long1 * pi / 180
    lat2 = lat2 * pi / 180
    long2 = long2 * pi / 180
    raio_da_terra =  6371 # km
    dLat = (lat2-lat1) #diferença das latitudes dos pontos em radianos
    dLon = (long2-long1) #diferença das longitudes dos pontos em radianos
    a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon/2) * Math.sin(dLon/2)
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
    distancia = raio_da_terra * c * 1000 #em metros
    return distancia
    
  end
  
end

app/views/estabelecimentos/_form.html.erb
<%= form_for(@estabelecimento) do |f| %>
  <% if @estabelecimento.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@estabelecimento.errors.count, "error") %> o estabelecimento nao pode ser salvo:</h2>
    <ul>
    <% @estabelecimento.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :gostei %><br />
    <%= f.text_field :gostei %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit "ok"%>
  </div>
<% end %>

app/views/estabelecimentos/busca.html.erb
<h1>Busca de Estabelecimentos</h1>
 
<table>
  <tr>
    <th>Nome</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @lista.each do |estabelecimento| %>
  <tr>
    <td><%= estabelecimento.nome %></td>
	<td><%= link_to 'Exibir', estabelecimento %></td>
  </tr>
<% end %>
</table>
 
<br />

app/views/estabelecimentos/create.html.erb
<h1>Estabelecimentos#create</h1>
<p>Find me in app/views/estabelecimentos/create.html.erb</p>

app/views/estabelecimentos/destroy.html.erb
<h1>Estabelecimentos#destroy</h1>
<p>Find me in app/views/estabelecimentos/destroy.html.erb</p>

app/views/estabelecimentos/edit.html.erb
<h1>Alterando estabelecimento</h1>
 
<%= render 'form' %>
 
<%= link_to 'Exibir', @estabelecimento %> |
<%= link_to 'Voltar', estabelecimentos_path %>

app/views/estabelecimentos/index.html.erb
<h1>Estabelecimentos</h1>
 
<table>
  <tr>
    <th>Nome</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @lista.each do |estabelecimento| %>
  <tr>
    <td><%= estabelecimento.nome %></td>
	<td><%= link_to 'Exibir', estabelecimento %></td>
    <td><%= link_to 'Editar', edit_estabelecimento_path(estabelecimento) %></td>
    <td><%= link_to 'Deletar', estabelecimento, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'Novo estabelecimento', new_estabelecimento_path %> 

app/views/estabelecimentos/new.html.erb
<h1>Novo estabelecimento</h1>
 
<%= render 'form' %>

<%= link_to 'Voltar', estabelecimentos_path %>

app/views/estabelecimentos/proximos.html.erb
<h1>Estabelecimentos Próximos</h1>
 
<table>
  <tr>
    <th>Nome</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @lista.each do |estabelecimento| %>
  <tr>
    <td><%= estabelecimento.nome %></td>
	<td><%= link_to 'Exibir', estabelecimento %></td>
  </tr>
<% end %>
</table>
 
<br />

app/views/estabelecimentos/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Nome:</b>
  <%= @estabelecimento.nome %>
</p>
 
<p>
  <b>Endereco:</b>
  <%= @estabelecimento.endereco %>
</p>
 
<p>
  <b>Telefone:</b>
  <%= @estabelecimento.telefone %>
</p>

<p>
  <b>Gostei:</b>
  <%= @estabelecimento.gostei %>
</p>

<p>
  <b>Favorito</b>
  <%= @estabelecimento.favorito %>
</p>

<p>
  <b>Produtos</b><br>
  <% @estabelecimento.produtos.each do |produto| %>
  <%= 	Preco.where(["produto_id = ? and estabelecimento_id = ?", produto.id, @estabelecimento.id])[0].valor %></tab>
  <%=	produto.nome  %> 
  <br> 
  <% end %>
</p>

<p>
  <b>Caracteristicas</b><br>
  <% @estabelecimento.caracteristicas.each do |caracteristica| %>
  <%=	caracteristica.nome  %> 
  <br> 
  <% end %>
</p>

 
<%= link_to 'Editar', edit_estabelecimento_path(@estabelecimento) %> |
<%= link_to 'Voltar', estabelecimentos_path %>

app/views/estabelecimentos/update.html.erb
<h1>Estabelecimentos#update</h1>
<p>Find me in app/views/estabelecimentos/update.html.erb</p>