config/routes.rb
Restserveruff::Application.routes.draw do

  match '/estabelecimentos/proximos', :controller => 'estabelecimentos', :action => 'proximos'
  match '/estabelecimentos/busca', :controller => 'estabelecimentos', :action => 'busca'
  match '/usuarios/login', :controller => 'usuarios', :action => 'login'
  
  resources :usuarios, :produtos, :estabelecimentos, :caracteristicas, :precos
  
  resources :usuarios do
    resources :favoritos
  end

end

app/models/caracteristica.rb
class Caracteristica < ActiveRecord::Base
  attr_accessible :nome
  has_and_belongs_to_many :estabelecimentos
end

app/controllers/caracteristicas_controller.rb
class CaracteristicasController < ApplicationController
  def new
    @caracteristica = Caracteristica.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @caracteristica }
    end
  end

  def create
    @caracteristica = Caracteristica.new(params[:caracteristica])

    respond_to do |format|
      if @caracteristica.save
        format.html  { redirect_to(@caracteristica, :notice => 'O Caracteristica foi criada.') }
        format.json  { render :json => @caracteristica, :status => :created, :location => @caracteristica }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @caracteristica.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @caracteristica = Caracteristica.find(params[:id])

    respond_to do |format|
      if @caracteristica.update_attributes(params[:caracteristica])
        format.html  { redirect_to(@caracteristica, :notice => 'O Caracteristica foi atualizada.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @caracteristica.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @caracteristica = Caracteristica.find(params[:id])
  end

  def destroy
    @caracteristica = Caracteristica.find(params[:id])
    @caracteristica.destroy

    respond_to do |format|
      format.html { redirect_to caracteristicas_url }
      format.json { head :no_content }
    end
  end

  def index
    @lista = Caracteristica.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @lista }
    end
  end

  def show
    @caracteristica = Caracteristica.find(params[:id])

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @caracteristica }
    end

  end
end

app/helpers/caracteristicas_helper.rb
module CaracteristicasHelper
end

app/views/caracteristicas/_form.html.erb
<%= form_for(@caracteristica) do |f| %>
  <% if @caracteristica.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@caracteristica.errors.count, "error") %> a caracteristica nao pode ser salva:</h2>
    <ul>
    <% @caracteristica.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit "ok"%>
  </div>
<% end %>

app/views/caracteristicas/create.html.erb
<h1>Caracteristicas#create</h1>
<p>Find me in app/views/caracteristicas/create.html.erb</p>

app/views/caracteristicas/destroy.html.erb
<h1>Caracteristicas#destroy</h1>
<p>Find me in app/views/caracteristicas/destroy.html.erb</p>

app/views/caracteristicas/edit.html.erb
<h1>Alterando caracteristica</h1>
 
<%= render 'form' %>
 
<%= link_to 'Exibir', @caracteristica %> |
<%= link_to 'Voltar', caracteristicas_path %>

app/views/caracteristicas/index.html.erb
<h1>Caracteristicas</h1>
 
<table>
  <tr>
    <th>Nome</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @lista.each do |caracteristica| %>
  <tr>
    <td><%= caracteristica.nome %></td>
    <td><%= link_to 'Editar', edit_caracteristica_path(caracteristica) %></td>
    <td><%= link_to 'Deletar', caracteristica, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'Novo caracteristica', new_caracteristica_path %> 

app/views/caracteristicas/new.html.erb
<h1>Novo caracteristica</h1>
 
<%= render 'form' %>

<%= link_to 'Voltar', caracteristicas_path %>

app/views/caracteristicas/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Nome:</b>
  <%= @caracteristica.nome %>
</p>

 
<%= link_to 'Editar', edit_caracteristica_path(@caracteristica) %> |
<%= link_to 'Voltar', caracteristicas_path %>

app/views/caracteristicas/update.html.erb
<h1>Caracteristicas#update</h1>
<p>Find me in app/views/caracteristicas/update.html.erb</p>